source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'pry'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'capybara'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'thin'
gem 'tux'


# source 'http://rubygems.org'
# ​
# gem 'activerecord', :require => 'active_record'
# gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
# ​
# gem 'sinatra'
# gem 'sqlite3'
# gem 'tux'
# gem 'capybara'
# gem 'pry'
# gem 'pry-nav'
# gem 'rake'
# gem 'rspec'
# gem 'rack-test'
# gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
# gem 'require_all'
# gem 'sinatra'
#     gem 'activerecord', :require => 'active_record'
#     gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
#     gem 'rake'
#     gem 'require_all'
#     gem 'sqlite3'
#     gem 'thin'
#     gem 'shotgun'
#     gem 'pry'
    
# group :test do
#       gem 'rspec'
#       gem 'capybara'
#       gem 'rack-test'
#       gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
#     end