source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'pry'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'thin', '~> 1.7', '>= 1.7.2'
gem 'tux'
gem 'capybara', '2.15.1'
