# Add seed data here. Seed your database with `rake db:seed`
sophie = Owner.create(name: "Sophie")
steve = Owner.create(name: "Steve")
yolanda = Owner.create(name: "Yolanda")
ann = Owner.create(name: "Ann")
larry = Owner.create(name: "Larry")
thomas = Owner.create(name: "Thomas")
imogen = Owner.create(name: "Imogen")
Pet.create(name: "Maddy", owner: sophie)
Pet.create(name: "Nona", owner: sophie)
Pet.create(name: "Snookie", owner: larry)
Pet.create(name: "Garfield", owner: imogen)
Pet.create(name: "Angry-cat", owner: thomas)
Pet.create(name: "Gandalf", owner: thomas)
Pet.create(name: "Patches", owner: ann)
Pet.create(name: "Drake", owner: ann)
Pet.create(name: "Baby", owner: yolanda)
