# Add seed data here. Seed your database with `rake db:seed`
sophie = Owner.create(name: "Sophie")
Pet.create(name: "Maddy", owner: sophie)
Pet.create(name: "Nona", owner: sophie)
tj = Owner.create(name: "TJ")
Pet.create(name: "Pils", owner: tj)
Pet.create(name: "Ghanoush", owner: tj)
shanni = Owner.create(name: "Shanni")
Pet.create(name: "Mogies", owner: shanni)
Pet.create(name: "Chaps", owner: shanni)
kat = Owner.create(name: "Kat")
Pet.create(name: "Ollie", owner: kat)
Pet.create(name: "Sammy", owner: kat)
